### ISSUE TITLE
Disable users link - 414 Error

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#143]
![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/62261480/db8a356d-daf2-4800-b30c-b2c701c5e5b2)

When clicking the "Disable users link" for a large response ([example](https://r9data.response.epa.gov/request/api/admin/accounts/responseproject/34/change/)) get an error:

![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/62261480/82b97177-dcd4-4a64-8bc0-5bba3bb6ac37)

**Comment by tbock** [comment]
I suspected this day would come.  This is because the number of accounts is so big that that resulting url is too long to list them all at once.  There is no other way to filter them so far as I know than how we are doing it now either.   Additional, we could allow disabling directly in the admin but this poses another issue.  We recently removed the list of account under a response b/c it grew too long and caused issues. 

Mostly I think I want to better understand how this was being used before making any changes.  Where you just going to disable a single user? If multiple how many? Is this becoming cumbersome enough to warrant a rethink on using the admin to manage a response? Should we allow disabling directly in the UI?   @abprins @jlherring

**Comment by tbock** [comment]
One random thought to leverage what we have is use the existing frontend and add a disable button to accounts that have been created using the tool (not ones that we just added to a group).

**Comment by abprins** [comment]
I like the idea of having a disable button for accounts created through the tool. Instead of a list of accounts that link to the GPO though, could it just link to the user page in the backend? Or to a view of the overall users list but filtered on the relevant response so we could batch disable accounts if necessary?

I rarely use this list view other than to get a sense of how many requests are coming through for various responses. I haven't actually used it for disabling users, but just for reference. As for the admin in general, I prefer it over the frontend for managing a response, I personally don't think that needs any rethinking.

**Comment by tbock** [comment]
I've just pushed the changes requested as I understand them to the new version (that supports geosecure).  Please review there and let me know if it works as expected. 

1) existing disable user link now goes to a filtered list within the application admin
2) there is a new admin action that allows you to multi select in the request list and choose ones to be disabled.

@abprins @jlherring

**Comment by abprins** [comment]
Yeah! This is exactly what I imagined, it looks great. I haven't tested the new batch disable account function yet, but I think this is an improvement for sure.
