### ISSUE TITLE
Add ability to disable a ResponseProject and notify sponsors/delegates

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#51]

**Comment by jlherring** [comment]
Think we keep this simple - some sort of checkbox or yes/no in the admin? Once a response is "disabled" it will no longer be an option in the response drop-down on the frontend. 

Quite a bit of discussion about who is responsible for actually tracking/cleaning up the accounts created after a response. In theory, this is always the Coordinator. In reality, .... meh. Rob mentioned maybe just sending an automated email to coordinators/delegates when a response is disabled? We add some sort of note about "your response is over. ok, now go take responsibility and remove users from groups or disable their accounts, as appropriate" - some kind of disclaimer and then we're out

**Comment by tbock** [comment]
I mean... yes... but I had always intentioned that we could build out some sort of automation around this.   Perhaps something like.  If account is created from this tool, not just added to groups, disable it once it has been inactive for X number of days.  I believe we've talked about this and there is some objection but it seems fairly safe to me to shutdown an account created during a response that hasn't been used in 60 days or so? 

Thoughts?

**Comment by jlherring** [comment]
I think that makes sense, but like you said - lots of disagreement on the topic. Not sure who has the final say?

**Comment by tbock** [comment]
I wonder what repercussions of disabling an account in agol are.

**Comment by torrin47** [comment]
Disabling accounts is pretty safe - it just prevents the user from logging in or resetting their password (which would need to be changed before a successful login after 60 days anyway). Otherwise the account and any content stays put. I guess it could collide with another user of the same name, but that's a pretty minor concern. Re-enabling is also easy.

I totally agree with the request to check a box to have a response no longer appear in the dropdown. I'm wary of any automated disabling/purging, and more a fan of notifying admins/sponsors/coordinators and handing them an easy button.

**Comment by tbock** [comment]
So... do we include a link to this easy button in the admin and/or send an email when a response is "disabled" to the sponsors with a reminder and link to the easy button? Can we logically build/is it possible to create a link to dashboard with query params set to filter users that are attached to the response?

**Comment by torrin47** [comment]
Our dashboard doesn't have a disable or delete function, we've always linked to AGOL for that, and their interface finally does accept multiple usernames - we have a ticket in our backlog to generate easy links like this where an admin could take action in bulk.

https://epa.maps.arcgis.com/home/organization.html?showFilters=false&start=1&view=table&sortOrder=desc&sortField=lastlogin&searchTerm=thultgre_EPA%20OR%20hultgren.torrin_EPA&searchBy=username#members

**Comment by tbock** [comment]
I guess the only question is... do we build link to everyone? We don't need to since we know which accounts were created for this response (at least through the tool).  Do we also remove EPA staff accounts from the list?   Just do EXT accounts that were created or all EXT accounts?

**Comment by tommckennon** [comment]
When would we want to notify admins/sponsors/coordinators of specific response projects? I'm thinking we still need a date field added to those response project records to know when it's useful to send that notification for the., It would also allow there to be a link to the old response projects only visible/accessible to the tool admin users in the edit dialog. Thus, I think it can be manual as well as more streamlined, but it seems there needs to be a date stamped to them. I can initiate them with a date that might make sense to initiate them with. Thoughts?

**Comment by tbock** [comment]
I think "Rob mentioned maybe just sending an automated email to coordinators/delegates when a response is disabled? We add some sort of note about "your response is over. ok, now go take responsibility and remove users from groups or disable their accounts, as appropriate" - some kind of disclaimer and then we're out" says it all. 

We disable the response. An email is sent.  That email includes the link to AGOL that pulls up the accounts that were actually created (see issue #80) and they can adjust things from there.

**Comment by tommckennon** [comment]
@tbock, I follow. @jlherring and @tbock , do we want to provide this disabling from within the admin console? What permissions if any for those who can disable project/responses? Would we want to notify admins/sponsors/coordinators on each of those email notices?

**Comment by tbock** [comment]
No additional permissions needed I think.  Just notify the assigned sponsors and their delegates.

**Comment by jlherring** [comment]
So @tbock @torrin47 are we agreeing that we notify users to go handle their business in AGOL? We do not put any kind of button that disables the users themselves?

Thinking it is configured in the admin. Jenny says "disable" on a response - it triggers an email to all sponsors/delegates. Sponsors/delegates come to the tool, look through their list of approved ppl (i.e. include #80), and then they go to town directly in AGOL?

**Comment by torrin47** [comment]
That's how we handle it in the dashboard. It's pretty easy to link directly to the GPO page for a single user to manage their properties and/or disable:

https://epa.maps.arcgis.com/home/organization.html?showFilters=false&start=1&view=table&sortOrder=desc&sortField=lastlogin&searchTerm=tbock03_EPA&searchBy=username#members

It's also possible to link to a table with many users, but because Esri, not via their username. Have to use unique identifiers which are a separate property of the user object:

https://epa.maps.arcgis.com/home/organization.html?showFilters=false&view=table&searchTerm=ff43d9afb62fc70b97eaeaa50d4e5bcb%20OR%20445169ea869b9eccd47f3e383af52958%20OR%20bce11a99883b4ff74625f3ca89eb308d%20OR%206eaf16a6cbbadfaf70c946bf1650459e%20OR%2027e8998bca5bde1c0f2c8b4d19b82728%20OR%203f2dd10173e6481f9f45f8c3362ceb26%20OR%200581676db0684a5c92d157d52ab18cd0%20OR%207d668d22673abacfb0c9079f100ef3a7%20OR%20c2a9ccc84ae5c34d3434bd9444ec6ab5%20OR%20a3906e73eb99e97c5066c6e9288138d0%20OR%203a2e92b913e6a80d1076bd07c57861ba%20OR%20d23649617b375a3ded17df31937ea5fb&sortOrder=asc&sortField=fullname#members

Pretty handy to be able to offer someone the ability to bulk Disable, but does require tracking those identifiers.

**Comment by tommckennon** [comment]
Thank you all for explaining these details.

**Comment by jlherring** [comment]
Not seeing this functionality anywhere @tbock. Maybe I'm missing it

**Comment by tbock** [comment]
https://r9data.response.epa.gov/apps/staging/request/api/admin/accounts/responseproject/7/change/?_changelist_filters=q%3Dfire
![image](https://user-images.githubusercontent.com/4040295/144621627-be31e54f-5397-4cdd-af94-258454a13c3e.png)

**Comment by jlherring** [comment]
great! didn't get an email, but not sure if that's a staging issue
